PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'wafrules' ('profID' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'onlyallowedip' INTEGER NOT NULL DEFAULT 0 , 'onlyallowedcountries' INTEGER NOT NULL DEFAULT 0 , 'proxyblock' INTEGER NOT NULL DEFAULT 0 , 'intelligenttest' INTEGER NOT NULL DEFAULT 0 , 'description' TEXT, 'requesthold' INTEGER NOT NULL DEFAULT 50, 'maxrcv' INTEGER NOT NULL DEFAULT 999999, intelligentmode varchar(100), title varchar(100));
INSERT INTO wafrules VALUES(1,0,0,0,0,'Default Rule with no specific blocking',50,999999,'NORMAL','Default');
INSERT INTO wafrules VALUES(2,0,0,1,1,'Blocks All requests from Proxy and VPN users',50,999999,'NORMAL','Proxy AND VPN blocker');
INSERT INTO wafrules VALUES(3,0,1,0,0,'Only Canada',50,999999,'NORMAL','None');
INSERT INTO wafrules VALUES(4,0,0,0,0,'Specific IP Block',50,999999,'NORMAL','Specific IP Block');
INSERT INTO wafrules VALUES(5,0,0,0,0,'Specific Country Block',50,999999,'NORMAL',NULL);
INSERT INTO wafrules VALUES(6,1,0,0,0,'Only Allow Ip',50,999999,'NORMAL','None');
INSERT INTO wafrules VALUES(7,1,1,1,1,'All type of blocking',100,999999,'NORMAL','All Switch Up');
CREATE TABLE IF NOT EXISTS 'ipclients' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'ip' TEXT NOT NULL, 'status' INTEGER NOT NULL DEFAULT 0, 'profID' INTEGER NOT NULL, FOREIGN KEY(profID) REFERENCES wafrules(profID));
INSERT INTO ipclients VALUES(3,'157.36.164.6',1,6);
INSERT INTO ipclients VALUES(4,'157.36.164.12',0,4);
INSERT INTO ipclients VALUES(7,'10.34.1.12',0,2);
CREATE TABLE IF NOT EXISTS 'countryrule' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'profID' INTEGER NOT NULL, 'country' TEXT NOT NULL, 'countryCode' TEXT NOT NULL, 'status' INTEGER NOT NULL DEFAULT 0, FOREIGN KEY(profID) REFERENCES wafrules(profID));
INSERT INTO countryrule VALUES(2,5,'United States','US',0);
INSERT INTO countryrule VALUES(3,3,'CANADA','CA',1);
INSERT INTO countryrule VALUES(4,3,'INDIA','IN',1);
CREATE TABLE CURPROF (profID INTEGER NOT NULL,FOREIGN KEY(profID) REFERENCES wafrules(profID));
INSERT INTO CURPROF VALUES(2);
CREATE TABLE CURSERV (host TEXT,port INTEGER);
INSERT INTO CURSERV VALUES('online.hnbgu.ac.in',80);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('wafrules',7);
INSERT INTO sqlite_sequence VALUES('ipclients',8);
INSERT INTO sqlite_sequence VALUES('countryrule',6);
COMMIT;
